// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://narxvgqpyaypshnnlgbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hcnh2Z3FweWF5cHNobm5sZ2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3OTg0MzgsImV4cCI6MjA2NzM3NDQzOH0.mdo9e3XmtnJ_JeCTxRgdfdUjXlaqQXTNUUUvltd5ELo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});